version: '3.9'

services:
 registry: 
   image: registry:2
   ports:
     - 5000:5000 
   deploy:
     replicas: 1 
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

networks:
  web:
    name: web 
    driver: overlay
